-- Insert sample data for legal_updates
INSERT INTO legal_updates (title, summary, full_content, author, subcategory, image_url, is_breaking, is_trending, published_date) VALUES
('Supreme Court Delivers Landmark Judgment on Digital Privacy Rights', 'The Supreme Court has ruled on a crucial case regarding digital privacy, setting new precedents for data protection in the digital age.', 'In a groundbreaking decision, the Supreme Court has established new guidelines for digital privacy rights, emphasizing the fundamental right to privacy in the digital realm. The court''s judgment addresses key concerns about data collection, storage, and usage by both government and private entities.', 'Justice Correspondent', 'Supreme Court', 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800', true, true, '2024-01-15'),
('High Court Rules on Employment Law Amendments', 'The High Court has provided clarity on recent amendments to employment legislation, affecting millions of workers nationwide.', 'The High Court''s recent ruling clarifies the interpretation and application of newly amended employment laws, providing much-needed guidance to employers and employees alike.', 'Legal Reporter', 'High Court', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800', false, true, '2024-01-14'),
('New Constitutional Interpretation on Fundamental Rights', 'A significant constitutional interpretation has emerged from the Supreme Court regarding the scope of fundamental rights.', 'The Supreme Court has expanded the interpretation of fundamental rights, particularly focusing on the right to equality and freedom of expression in the modern context.', 'Constitutional Expert', 'Supreme Court', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800', false, false, '2024-01-13'),
('High Court Addresses Corporate Governance Issues', 'Recent corporate governance disputes have been resolved through High Court intervention.', 'The High Court has set new precedents for corporate governance, addressing issues of transparency and accountability in corporate management.', 'Corporate Law Analyst', 'High Court', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', false, false, '2024-01-12'),
('Supreme Court on Environmental Protection Laws', 'Environmental protection receives constitutional backing through recent Supreme Court decision.', 'The Supreme Court has strengthened environmental protection laws, emphasizing the state''s duty to protect the environment for future generations.', 'Environmental Correspondent', 'Supreme Court', 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800', false, true, '2024-01-11');

-- Insert sample data for blogs
INSERT INTO blogs (title, summary, full_content, author, subcategory, image_url, is_breaking, is_trending, published_date) VALUES
('Understanding Constitutional Amendments in Modern Democracy', 'An in-depth analysis of how constitutional amendments shape democratic governance in contemporary times.', 'This comprehensive blog explores the process and impact of constitutional amendments, examining how they adapt democratic institutions to changing societal needs.', 'Dr. Sarah Mitchell', 'Constitutional Law', 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800', true, true, '2024-01-15'),
('Family Law Reforms: Impact on Modern Relationships', 'Exploring how recent family law reforms affect marriage, divorce, and child custody proceedings.', 'This detailed analysis examines the latest family law reforms and their practical implications for families navigating legal processes.', 'Family Law Expert', 'Family Law', 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=800', false, true, '2024-01-14'),
('Alternative Dispute Resolution in Commercial Conflicts', 'How ADR mechanisms are revolutionizing commercial dispute resolution.', 'This blog discusses the growing importance of alternative dispute resolution methods in commercial law, highlighting their efficiency and cost-effectiveness.', 'ADR Specialist', 'ADR Law', 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800', false, false, '2024-01-13'),
('Corporate Governance in the Digital Age', 'Examining how technology is reshaping corporate governance practices.', 'This analysis explores how digital transformation is changing corporate governance, from board meetings to shareholder communications.', 'Corporate Counsel', 'Corporate Law', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800', false, true, '2024-01-12'),
('Technology Law: Navigating AI and Data Protection', 'Understanding the legal challenges posed by artificial intelligence and data privacy.', 'This comprehensive guide examines the intersection of technology and law, focusing on AI regulation and data protection requirements.', 'Tech Law Advisor', 'Tech Law', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800', false, false, '2024-01-11');

-- Insert sample data for case_comments
INSERT INTO case_comments (title, summary, full_content, author, subcategory, image_url, is_breaking, is_trending, published_date) VALUES
('Analysis: Recent Supreme Court Decision on Privacy Rights', 'Detailed commentary on the Supreme Court''s latest privacy rights judgment and its implications.', 'This case comment provides comprehensive analysis of the Supreme Court''s recent decision on digital privacy rights, examining its legal precedents and future implications.', 'Senior Advocate', 'Case Updates', 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800', true, true, '2024-01-15'),
('Landmark Case: Corporate Liability in Environmental Damage', 'Commentary on a groundbreaking case establishing corporate environmental liability.', 'This detailed case comment analyzes a landmark judgment that expands corporate liability for environmental damage, setting new standards for corporate responsibility.', 'Environmental Lawyer', 'Landmark Cases', 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800', false, true, '2024-01-14'),
('Constitutional Bench Decision on Fundamental Rights', 'Analysis of the constitutional bench''s interpretation of fundamental rights.', 'This case comment examines the constitutional bench''s recent decision on fundamental rights, analyzing its impact on civil liberties and constitutional law.', 'Constitutional Scholar', 'Case Updates', 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800', false, false, '2024-01-13'),
('Precedent-Setting Case in Contract Law', 'Commentary on a case that sets new precedents in commercial contract interpretation.', 'This analysis explores a recent case that has established new precedents in contract law, particularly regarding force majeure clauses and contract interpretation.', 'Contract Law Expert', 'Landmark Cases', 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800', false, true, '2024-01-12'),
('Recent Judgment on Employment Rights', 'Analysis of a significant employment law case and its broader implications.', 'This case comment examines a recent employment law judgment, analyzing its impact on worker rights and employer obligations.', 'Employment Lawyer', 'Case Updates', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800', false, false, '2024-01-11');

-- Insert sample data for fair_review
INSERT INTO fair_review (title, summary, full_content, author, subcategory, image_url, is_breaking, is_trending, published_date) VALUES
('Judicial Review: Recent Supreme Court Performance Analysis', 'A balanced assessment of recent Supreme Court decisions and their impact on legal precedents.', 'This fair review examines the Supreme Court''s recent performance, analyzing key decisions and their contributions to legal jurisprudence while maintaining objectivity.', 'Judicial Analyst', 'Supreme Court Review', 'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800', true, true, '2024-01-15'),
('High Court Efficiency: A Year in Review', 'Comprehensive analysis of High Court operations and case disposal rates over the past year.', 'This review assesses High Court performance metrics, including case disposal rates, judgment quality, and administrative efficiency.', 'Court Observer', 'High Court Review', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800', false, true, '2024-01-14'),
('Legal Education Reform: Progress and Challenges', 'Evaluating recent reforms in legal education and their effectiveness.', 'This fair review examines the progress made in legal education reform, identifying successes and areas that still need improvement.', 'Education Specialist', 'Legal Education', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800', false, false, '2024-01-13'),
('Bar Council Initiatives: Impact Assessment', 'Analysis of recent Bar Council initiatives and their effectiveness in improving legal practice.', 'This review evaluates the impact of recent Bar Council initiatives on legal practice standards and professional development.', 'Legal Professional', 'Bar Council Review', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800', false, true, '2024-01-12'),
('Judicial Appointments: Transparency and Merit', 'Reviewing the judicial appointment process and recent improvements in transparency.', 'This analysis examines recent changes in the judicial appointment process, focusing on transparency measures and merit-based selection.', 'Judicial Reform Expert', 'Judicial Appointments', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', false, false, '2024-01-11');