// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdoczcmcueiztpgqinww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkb2N6Y21jdWVpenRwZ3Fpbnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzI3MzAsImV4cCI6MjA3MDMwODczMH0.dSPZlduTFZMn6rusQbrzy51vAZ3oWS8ontAEmTgajQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});